repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.7'  # pick a git hash / tag to point to
    hooks:
    - id: flake8
      language_version: python3.7
