group: travis_latest
dist: xenial  # required for Python >= 3.7
language: python
python: 3.7
cache: pip
services:
  - xvfb
install:
  # - pip install -r requirements.txt
  - pip install black flake8 wily
before_script:
  - black . --check
  - flake8 . --count --ignore=E203,W503 --max-complexity=10 --max-line-length=127 --show-source --statistics
  - git checkout -b branch_for_wily  # avoid wily "HEAD is a detached symbolic reference" error
  - wily build .
  - wily report --format HTML .
  - cat wily_report/index.html
script:
  - python DominoWorld.py  # Play some computer vs. computer games
notifications:
  email: false
