group: travis_latest
dist: xenial  # required for Python >= 3.7
language: python
python: 3.7
cache: pip
services:
  - xvfb
install:
  # - pip install -r requirements.txt
  - pip install black flake8 mypy vulture  # MonkeyType
before_script:
  - black . --check
  - flake8 . --count --ignore=E203,W503 --max-complexity=10 --max-line-length=127 --show-source --statistics
  - mypy .
script:
  - vulture *.py || true
  - ./DominoWorld.py  # Play some computer vs. computer games
  - ls *.toml || true
  #- monkeytype run DominoWorld.py  # Play some computer vs. computer games
  #- monkeytype list-modules
  #- monkeytype stub --diff DominoBoard
  #- monkeytype stub --diff DominoPlayer
  #- monkeytype stub --diff PlayedDomino
  #- monkeytype stub --diff TkdndDropTarget
  #- monkeytype stub --diff drawDomino
  #- monkeytype stub --diff tkDomino
  ## - monkeytype stub DominoWorld
  ## - monkeytype stub tkinter.dnd
notifications:
  email: false
