group: travis_latest
language: python
python: 3.8
cache: pip
services:
  - xvfb
install:
  # - pip install -r requirements.txt
  - pip install black flake8 mypy
  #- pip install graphviz pycallgraph
  #- pip install vulture
  #- pip install MonkeyType
before_script:
  - black . --check
  - flake8 . --count --max-complexity=10 --max-line-length=88 --show-source --statistics
  - mypy .
script:
  - ./DominoWorld.py  # Play some computer vs. computer games
  #- pycallgraph graphviz -- ./DominoWorld.py  # Play some computer vs. computer games

  #- vulture *.py || true
  # - ./DominoWorld.py  # Play some computer vs. computer games
  - ls -l *.toml | ./cat_biggest.py

  #- monkeytype run DominoWorld.py  # Play some computer vs. computer games
  #- monkeytype list-modules
  #- monkeytype stub --diff DominoBoard
  #- monkeytype stub --diff DominoPlayer
  #- monkeytype stub --diff PlayedDomino
  #- monkeytype stub --diff TkdndDropTarget
  #- monkeytype stub --diff drawDomino
  #- monkeytype stub --diff tkDomino
  ## - monkeytype stub DominoWorld
  ## - monkeytype stub tkinter.dnd
notifications:
  email: false
