group: travis_latest
dist: xenial  # required for Python >= 3.7
language: python
python: 3.7
cache: pip
services:
  - xvfb
install:
  # - pip install -r requirements.txt
  - pip install black flake8 MonkeyType mypy
before_script:
  - black . --check
  - flake8 . --count --ignore=E203,W503 --max-complexity=10 --max-line-length=127 --show-source --statistics
  - mypy .
script:
  - monkeytype run DominoWorld.py  # Play some computer vs. computer games
  - monkeytype list_modules
  - monkeytype stub DominoWorld
  - monkeytype stub tkinter.dnd
  - monkeytype stub
notifications:
  email: false
