#!/usr/bin/env -S uv run --script

"""
Running this script should open in the local web browser a PyScript-based graphical user interface for playing racehorse dominos.

The game board should be displayed to look similar to images/tkDomino.py.png but using Pyodide instead of tkinter.
The dominos should be based on the files generated by dominos_svg.py
Each player should be dealt 7 random dominos which appear in their boxes at the top and bottom of the UI.
The remaining dominos should be placed face-down (no dots showing) in the boneyard.
The first player should be able to drag one domino from their hand into the play area.
"""

# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "beautifulsoup4",
#     "httpx",
#     "pydantic",
# ]
# ///
