[33]
left = "43"
right = "31"
up = "63"
down = "35"
orientation = "vertical"

[43]
left = "64"
right = "33"
orientation = "horizontal"

[31]
left = "33"
orientation = "horizontal"

[64]
left = "06"
right = "43"
orientation = "horizontal"

[63]
down = "33"
orientation = "vertical"

[06]
left = "50"
right = "64"
orientation = "horizontal"

[35]
up = "33"
down = "55"
orientation = "vertical"

[50]
left = "45"
right = "06"
orientation = "horizontal"

[55]
up = "35"
orientation = "horizontal"

[45]
left = "04"
right = "50"
orientation = "horizontal"

[04]
right = "45"
orientation = "horizontal"
